### ISSUE TITLE
Token is not returned when calling msRestNodeAuth.loginWithAppServiceMSI()

### ISSUE THREAD

**Issue by jmiddleton** [Azure/ms-rest-nodeauth#102]
Should this method return await creds.getToken() instead of creds?

https://github.com/Azure/ms-rest-nodeauth/blob/4bbceb1dc3c6c9928b6c8257a4b3d98b8e71913a/lib/login.ts#L887

Samples Azure function:

```
const msRestNodeAuth = require("@azure/ms-rest-nodeauth");

module.exports = async function (context) {

    try {
        const msiTokenRes = await msRestNodeAuth.loginWithAppServiceMSI();

        context.log.info("MSI Token response: ");
        //call getToken() here again to get accessToken
        const token= await msiTokenRes.getToken();
       context.log.info(token);

    } catch (err) {
        console.error(err);
    };
};
```

**Comment by ramya-rao-a** [comment]
@jmiddleton, 
Thanks for reporting.

The various methods exposed in this package to aid with auth, all return a credential object that follows the interface TokenClientCredentials. So making the change you suggested to `_withAppServiceMSI()` to return just the access token would violate the api contract.

But, this brings up a good point on why even have the `await creds.getToken()` in `_withAppServiceMSI()`. We could have simply returned the creds as is. We will look into this.

Meanwhile, can you share if this has caused any problems in your code or is this an optimization you were looking for?

@daviwil,
I see this pattern in both `loginWithVmMSI()` and `loginWithAppServiceMSI()`. 
The only advantage I see of this model is that any errors from the user eventually calling `getToken()` on the credential is now front loaded to the time of the credential creation. Thoughts?

**Comment by daviwil** [comment]
@ramya-rao-a yep, I think that's the idea, surfacing auth errors as soon as possible.  I see `creds.getToken()` calls in many places when credentials are being created so I think this is the expected pattern for this library.

**Comment by jmiddleton** [comment]
Thanks for your reply, currently we don't have any problem. I was able to get my code working so no issues.

You can close the ticket if all good.

thanks,
Jorge
