### ISSUE TITLE
An unexpected error occured while fetching the AAD Token.

### ISSUE THREAD

**Issue by MarekMind** [Azure/ms-rest-nodeauth#106]
**Package Version**: _______
```
@azure/ms-rest-nodeauth": {
      "version": "3.0.5",
      "resolved": "https://registry.npmjs.org/@azure/ms-rest-nodeauth/-/ms-rest-nodeauth-3.0.5.tgz",
      "requires": {
        "@azure/ms-rest-azure-env": "^2.0.0",
        "@azure/ms-rest-js": "^2.0.4",
        "adal-node": "^0.1.28"
      }
    }
```

**Describe the bug**
After AppService restart, MSI endpoint which generates the token for services, stopped working for some of the staging and production services, few of development services are able to generate the token while other doesn't.
We tried to:

1. Re-deploy the App Service Docker container.
2. Re-apply identity on App Service (disable and enable), which generates new MSI_ENDPOINT and MSI_SECRET.
3. Call MSI_ENDPOINT manually via HTTP API (including required X-IDENTITY-HEADER header) returns the same error.
4. Tried to use DefaultAzureCredential class (`ManagedIdentityCredential authentication failed.(status code 400). More details: unknown_error(status code 500). More details: An unknown error occurred and no additional details are available.`).

All of those things didn't solve the issue itself.

**To Reproduce**
Unable to reproduce as it was working fine for several weeks and suddenly stopped working, our development App Service instance is working fine, while staging is not able to use MSI.

**Expected behaviour**
**MSI Token** to be used for Azure services

**Additional context**
```
2020-09-28T09:11:40.128854312Z {"trace":"keyvault_load_config_error","level":"error","message":"Invalid token response, did not find tokenType. Response body is: {\"statusCode\":500,\"message\":\"An unexpected error occured while fetching the AAD Token.\",\"correlationId\":\"xxxx\"}","timestamp":"2020-09-28T09:11:40.128Z"}
```

**Comment by daviwil** [comment]
Hi @MarekMind, this sounds like a potential issue with the MSI service itself.  Are you still experiencing the same issue or has it resolved?

**Comment by MarekMind** [comment]
We are experiencing this error now in staging and production, for all our services...

**Comment by daviwil** [comment]
From this line in the original issue description, I understand that you tried to access the MSI endpoint directly via HTTP request and still received the 500 error, is that correct?

> 3. Call MSI_ENDPOINT manually via HTTP API (including required X-IDENTITY-HEADER header) returns the same error.

I will see if I can locate someone internally to help investigate this issue.

**Comment by ramya-rao-a** [comment]
Apologies for this thread going silent.
Our recommendation is indeed to move to using credentials from the `@azure/identity` package.
If you are still seeing issues with using the credentials from the `@azure/identity` package, please log an issue at https://github.com/azure/azure-sdk-for-js
