### ISSUE TITLE
LoginWithMSI on AKS

### ISSUE THREAD

**Issue by ayush1303** [Azure/ms-rest-nodeauth#109]
I am in the progress to move my application from App Service to AKS(Kubernetes).
There are many azure resources that I am connecting to from my application using ms-rest-nodeauth via using the `loginWithAppServiceMSI` method which seems not to work with AKS setup.

Do we have any alternative or workaround for the same ?

**Describe the solution you'd like**
Connect to Azure using MSI on AKS

**Comment by sadasant** [comment]
@ayush1303 Hello hello!

I think you will be able to use `loginWithAppServiceMSI` with AKS. To test this I would need several days, but you can try the following in the mean time.

The main difference between App Service and AKS should be the how the Identity Endpoint and the secrets are passed through to ms-rest-nodeauth, and perhaps the MSI API version.

I could be wrong, but I believe you should be able to connect by calling `loginWithAppServiceMSI` with an object similar to:

```ts
{
  clientId: "<your-client-id",
  msiEndpoint: process.env.IDENTITY_ENDPOINT || process.env.MSI_ENDPOINT,
  msiSecret: process.env.IDENTITY_HEADER || process.env.MSI_SECRET,
  // You might need to add the following line, though I am not sure of the correct version in this exact moment:
  // msiApiVersion: "2019-07-01-preview"
}
```

Please let us know if that works while I find  the time to set up a test environment.

**Comment by ayush1303** [comment]
@sadasant , Hello..

I tried with passing options as you mentioned but it didn't work for me sure but `process.env.IDENTITY_HEADER || process.env.MSI_SECRET` none of these happens to be available for AKS setup.

So I tried athor way around and it worked for me !!! 

What I did is,
1. Explicitly fetched msi token form MSI_ENDPOINT -> 
```
const url = `${process.env.MSI_ENDPOINT_1}?resource=https://management.azure.com&api-version=${process.env.API_VERSION}}`;
const headers =  {
          Metadata: true,
        };
// Ignored error handling for readablity
const response = await got .get(url, { headers })
const details = JSON.parse(response.body);
const token =  details.access_token; // MSI TOKEN !!!
```

2. Then made credential object using
```
function getCredentialForToken(accessToken) {
  return {
    signRequest: (request) => {
      if (!request.headers) request.headers = new HttpHeaders();
      request.headers.set("Authorization", `Bearer ${accessToken}`);
      return Promise.resolve(request);
    }
  };
}
```

3. Used this credential for further operations

Some additional things I faced not related to ms-rest-node-auth but might help someone.

For some of resources, I have got credentials with using `DefaultAzureCredential` of @azure/identity, Now there was a weird issue I faced in order to achieve the above case I passed MSI_ENDPOINT as env variable with its default value but it was causing some issue with @azure/identity and was giving an error about `authority_url not found` (maybe the env variable was being changed internally ???). Finally I changed my env variable to something else ie. MSI_ENDPOINT_1 and it worked !!!

**Comment by sadasant** [comment]
@ayush1303

Hello hello! That's awesome!

I didn't know you were also working with @azure/identity. This makes sense. If you use @azure/identity only, without any extra effort from your side (like setting this environment variable), does it authenticate? I believe it should, but I wanted to confirm.

We're currently in this intermediate scenario in which ms-rest-nodeauth is still the recommended library for management-plane clients, while we're only adding features to @azure/identity. Is it the case for you that you need to use ms-rest-nodeauth and @azure/identity because you're using both management plane and data plane clients? Or, what clients are you using?

Your feedback is appreciated. If you think this issue has been resolved, please close this at any point. Regardless of the status of this issue, I still want to know more information about your case. Thank you for your time!

**Comment by ayush1303** [comment]
Hello @sadasant 

Yes for azure key vault and blob storages I have used @azure/identity and for other arm libraries I have used approach above as loginWithAppService with passing those option didn't worked for me.

Though I am closing the issue please let me know if I can improve.

**Comment by sadasant** [comment]
@ayush1303 Thank you so much for your feedback! We'll be working on adding support for @azure/identity on the ARM libraries later this year. Good luck and you're welcome back here anytime!
