### ISSUE TITLE
AADSTS900382: Confidential Client is not supported in Cross Cloud request

### ISSUE THREAD

**Issue by padmapriya21** [Azure/ms-rest-nodeauth#110]
**Package Version**:     3.0.6
- [ ] **nodejs**
   - **nodejs version**: ___10.14.1___
   
### _**When trying to invoke data factory in government cloud using ms-rest-nodeauth it's throwing an error saying Confidential Client is not supported in Cross Cloud request.**_ 

`500 Error: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\n`

https://www.npmjs.com/package/@azure/arm-datafactory ---- using this package for data factory

### **_The issue is only in government cloud._**

**To Reproduce**
`  let authres = await msRestNodeAuth.loginWithServicePrincipalSecretWithAuthResponse(config.clientID, config.clientIDAppSecret, tenantId);
            let client = new DataFactory.DataFactoryManagementClient(authres.credentials, config.subscriptionID); `

**Expected behavior**

Expected to invoke data factory in government cloud successfully

**Comment by sadasant** [comment]
@padmapriya21 Hello! I'll be doing my best to have an answer for you.

I'll be talking with my team to figure out what's going on. I will come back as soon as I have a response.

**Comment by padmapriya21** [comment]
> @padmapriya21 Hello! I'll be doing my best to have an answer for you.
> 
> I'll be talking with my team to figure out what's going on. I will come back as soon as I have a response.

@sadasant Any response??

**Comment by padmapriya21** [comment]
@sadasant  Any response for the above mentioned issue?

**Comment by sadasant** [comment]
@padmapriya21 not yet! I'll try to give an answer between today and tomorrow.

**Comment by sadasant** [comment]
@padmapriya21 Hello! I have an answer for you.

For this task you'll need to use `@azure/ms-rest-nodeauth` with another library: `@azure/ms-rest-azure-env`.

`@azure/ms-rest-azure-env` allows you to load different clouds other than the Azure public cloud. You do that by picking the object that has the properties that match the cloud you're working with, or by specifying your own set of properties. The clouds with fully defined properties are: `AzureCloud` (the default one), `ChinaCloud`, `USGovernment` and `GermanCloud`. You can see them here: [link to source](https://github.com/Azure/ms-rest-azure-env/blob/master/lib/azureEnvironment.ts).

To use, let's say, the `USGovernment` cloud, you would need to change your code with the following:

```js
import * as msRestNodeAuth from "@azure/ms-rest-nodeauth";
import { Environment } from "@azure/ms-rest-azure-env";

// Here we specify the USGovernment cloud.
const environment = Environment.USGovernment;

const loginOptions = { environment };

// Make sure to have the `config` object available at this point.

// The `loginOptions` we defined earlier is passed through as the last parameter.
const authres = await msRestNodeAuth.loginWithServicePrincipalSecretWithAuthResponse(config.clientID, config.clientIDAppSecret, tenantId, loginOptions);

// If the correct cloud is picked, you shouldn't see the same error anymore.
// Meaning you shouldn't see the error that contains: `Confidential Client is not supported in Cross Cloud request.`.
const client = new DataFactory.DataFactoryManagementClient(authres.credentials, config.subscriptionID);
```

I believe that `@azure/ms-rest-azure-env` is the key to find the solution to this issue. Please take your time to try it and let us know about your experience! We're here to help.

**Comment by sadasant** [comment]
@padmapriya21 Hello! Did my previous approach solve this issue? Please let us know how else we can help! Thank you for your time.

**Comment by padmapriya21** [comment]
Thanks a lot @sadasant .
It worked out after following your approach.
