### ISSUE TITLE
Update adal-node  package to fix request depricated error

### ISSUE THREAD

**Issue by acotty** [Azure/ms-rest-nodeauth#125]
**Package Version**:  3.0.9

**Describe the bug**
When installing the following issues are shown due to the use of an superseded adal-node package:

@azure/ms-rest-nodeauth > adal-node > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
@azure/ms-rest-nodeauth > adal-node > request > har-validator@5.1.5: this library is no longer supported

**To Reproduce**
1. install package

**Expected behavior**
no message shown due to depricated packages.

The package I am installing is mssql, so this needs to be fixed in ms-rest-nodeauth and then the tedious package and be updated and then mssql.....

**Comment by ramya-rao-a** [comment]
Thanks for reporting @acotty 

@sadasant, Looks like updating `@azure/ms-rest-browserauth` to use the latest adal-node should solve this problem as the latest version does not depend on `request` anymore.

Let's make that update, test and release a patch update for `@azure/ms-rest-browserauth`

**Comment by sadasant** [comment]
@ramya-rao-a ok ok! I'll do that this week.
