### ISSUE TITLE
Ref doc issue - ms-rest-nodeauth loginWithAppServiceMSI()

### ISSUE THREAD

**Issue by diberry** [Azure/ms-rest-nodeauth#127]
This [ref doc](https://docs.microsoft.com/en-us/javascript/api/%40azure/ms-rest-nodeauth/?view=azure-node-latest#loginwithappservicemsi--) method doesn't have enough information to use. 
* Is there supposed to be a `%40` before azure in the URL? 
* Is there more information about the AppServiceMSI or a link to some other doc? 
* 3rd paragraph looks incorrectly formatted

![image](https://user-images.githubusercontent.com/41597107/94735753-11f46c00-0320-11eb-9b07-e735676699a2.png)

**Comment by ramya-rao-a** [comment]
> Is there supposed to be a %40 before azure in the URL?

Not required. Do you recall which link you clicked to get here? That can tell us what needs to be fixed where

> Is there more information about the AppServiceMSI or a link to some other doc?

If you have an aka.ms link that is language agnostic, that would be useful

> 3rd paragraph looks incorrectly formatted

Created #133

**Comment by ramya-rao-a** [comment]
@sadasant Please close this issue after ensuring the docs have been updated post releasing 3.1.0 of `@azure/ms-rest-nodeauth`

**Comment by sadasant** [comment]
Released! https://www.npmjs.com/package/@azure/ms-rest-nodeauth/v/3.1.0

**Comment by sadasant** [comment]
The docs haven’t been updated. I’m investigating.

**Comment by sadasant** [comment]
Ok now it’s fixed! https://docs.microsoft.com/en-us/javascript/api/%40azure/ms-rest-nodeauth/?view=azure-node-latest#loginWithAppServiceMSI__ closing
