### ISSUE TITLE
Update the project to use msal node

### ISSUE THREAD

**Issue by jajens** [Azure/ms-rest-nodeauth#128]
Currently this project is using adal-node which is in maintenance-only status (https://github.com/AzureAD/azure-activedirectory-library-for-nodejs) and is causing an S360 alert for EOL.

**Comment by ramya-rao-a** [comment]
There are no plans to update this project to use msal node.

We will instead invest time in some docs to show how you could move to using the new `@azure/identity` instead.
See https://github.com/Azure/ms-rest-nodeauth/issues/129

I would recommend using the adapter `AzureIdentityCredentialAdapter` from `@azure/ms-rest-js` that can convert a credential from the new `@azure/identity` to the same shape as what you get from `@azure/ms-rest-nodeauth`

**Comment by ramya-rao-a** [comment]
The credentials from `@azure/ms-rest-nodeauth` are mainly used in the Azure ARM packages. These packages follow the naming convention of `@azure/arm-*`. All such packages have been updated to use credentials from the newer `@azure/identity`. Please checkout the [examples for @azure/identity](https://aka.ms/azsdk/js/identity/examples) to understand how to create credentials using the new package.

Meanwhile, we shall be using #129 to create a migration guide showing the new counterparts to each of the credential in `@azure/ms-rest-nodeauth`.
