### ISSUE TITLE
  @azure/arm-kusto (6.2.1) : vulnerability , Misinterpretation of malicious XML input

### ISSUE THREAD

**Issue by pkraj0** [Azure/ms-rest-nodeauth#134]
"@azure/arm-kusto": "^6.2.1",

npm audit

                       === npm audit security report ===                        

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Moderate        Misinterpretation of malicious XML input

  Package         xmldom

  Patched in      >=0.7.0

  Dependency of   @azure/ms-rest-nodeauth

  Path            @azure/ms-rest-nodeauth > adal-node > xmldom

  More info       https://npmjs.com/advisories/1769

**Comment by ramya-rao-a** [comment]
Looks like adal-node's dependency on xmldom is via `"xmldom": ">= 0.1.x"`

So, whenever an update to xmldom is published, we should get the fix for free.

Therefore, closing this issue.

**Comment by ranarn** [comment]
They most likely wont update 0.1.x (last update Dec 19, 2019)
You need to update to a new feature version. 0.x

**Comment by ramya-rao-a** [comment]
If the dependency was listed as `^0.1.x` then yes, the next version 0.7.0 that has the fix will not be picked up.
But the dependency is listed as `>= 0.1.x` which should cover ALL versions greater than 0.1

**Comment by ranarn** [comment]
> If the dependency was listed as `^0.1.x` then yes, the next version 0.7.0 that has the fix will not be picked up.
> But the dependency is listed as `>= 0.1.x` which should cover ALL versions greater than 0.1

So you are saying we wont get a fix for this? Since 0.1.x will not likely ever be updated.

**Comment by ramya-rao-a** [comment]
When xmldom 0.7.0 gets released, it will contain the fix.
Users of `@azure/ms-rest-nodeauth` will get that fix for free when they do a fresh `npm install` in their application which will pull in 0.7.0 of xmldom

I am saying that there are no changes needed in the `@azure/ms-rest-nodeauth` package or the `adal` package for customers to receive the fix once 0.7.0 of xmldom is released.

**Comment by ramya-rao-a** [comment]
Please subscribe to https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4011 for more on this issue.

**Comment by jasonnutter** [comment]
`ada-node@0.2.3` has been released with `@xmldom/xmldom`.

**Comment by ramya-rao-a** [comment]
Thanks @jasonnutter!
