### ISSUE TITLE
xmldom security vulnerability for adal-node dependency

### ISSUE THREAD

**Issue by skhilliard** [Azure/ms-rest-nodeauth#135]
Node version: 14.15.5
Package version: 3.0.10

Security vulnerabilities for xmldom (would have to reference latest @xmldom/xmldom to address):

Path: mssql > tedious > @azure/ms-rest-nodeauth > adal-node > xmldom
Path: mssql > tedious > adal-node > xmldom
Misinterpretation of malicious XML input: https://npmjs.com/advisories/1769

It seems like the problem is that adal-node has been marked read only, but it needs to have security updates applied.

I also posted this issue on the mssql github page, but it was immediately closed:   #[https://github.com/tediousjs/node-mssql/issues/1300](url)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @skhilliard 

This is being tracked for adal-node at https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4011

Once they release an update, you should get it for free when you re install your packages

**Comment by jasonnutter** [comment]
@skhilliard @ramya-rao-a `adal-node@0.2.3` has been released with `@xmldom/xmldom`.

**Comment by skhilliard** [comment]
Thanks for the quick response!  Any thoughts as to a timeline for when the items "up the chain" will start using this update?

Path: mssql > tedious > @azure/ms-rest-nodeauth > adal-node > xmldom
Path: mssql > tedious > adal-node > xmldom

**Comment by jasonnutter** [comment]
It looks like tedious is migrating to `@azure/identity`, and will no longer rely on `adal-node`: https://github.com/tediousjs/tedious/pull/1328
