### ISSUE TITLE
Add support for service principal login with certificates

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-nodeauth#16]
Today we only support service principal login with secret/password. We need to support SP login with certificates as well. 

For reference, you can take a look at this piece of code: https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/authentication/adalAuthForServicePrincipal.js#L55

**Comment by amarzavery** [comment]
fixed by #53

**Comment by wudong** [comment]
Does this support passport protected certificate ?

**Comment by gettek** [comment]
^+1 Same here we use password protected certs :(
