### ISSUE TITLE
Change login.withServicePrincipalSecret()'s return type to ApplicationTokenCredentials

### ISSUE THREAD

**Issue by daschult** [Azure/ms-rest-nodeauth#49]
**Is your feature request related to a problem? Please describe.**
Previously [login.withServicePrincipalSecret()](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/login.ts#L616) returned an [ApplicationTokenCredentials](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/applicationTokenCredentials.ts#L9) object. After some refactoring took place, the return type changed to [TokenCredentialsBase](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/tokenCredentialsBase.ts#L10), even though the return value is always an [ApplicationTokenCredentials](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/applicationTokenCredentials.ts#L9).

**Describe the solution you'd like**
It would be good if [login.withServicePrincipalSecret()](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/login.ts#L616) could go back to returning an [ApplicationTokenCredentials](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/applicationTokenCredentials.ts#L9). The easiest way to do this would be to cast the return value as an [ApplicationTokenCredentials](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/applicationTokenCredentials.ts#L9) object.

**Describe alternatives you've considered**
You could also change [AuthResponse](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/login.ts#L90) to be a generic type where the type parameter is the type of the [credentials](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/login.ts#L94) property. That way all of the `login...()` methods could get accurate type information about their return value.

**Comment by bterlson** [comment]
@daschult is this a fix we can make relatively soon? We're looking to migrate Event Hub libraries to the shiny new auth libs and this change will impact existing customers...

**Comment by ramya-rao-a** [comment]
FYI, I have submitted a PR to fix this issue. Please see https://github.com/Azure/ms-rest-nodeauth/pull/50

**Comment by ramya-rao-a** [comment]
This issue can be closed now as the PR #50 has been merged and version 0.9.2 of this library has the fix
