### ISSUE TITLE
Breaking change in a patch version

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/ms-rest-nodeauth#69]
**Package Version**: 2.0.3
- [x] **nodejs**
   - **nodejs version**: 10.15.3
   - **os name/version**: Windows 10

**Describe the bug**
I'm getting #67 but the other way around. My app depends on 

```
"@azure/ms-rest-azure-js":       "~1.3.8",
"@azure/ms-rest-nodeauth":       "~2.0.2",
```

Both used to be the latest versions of corresponding libraries not so long ago. The latest patch version `2.0.3` of `ms-rest-nodeauth` updated to `ms-rest-js` version `2.0.3` which is not compatible to the old `ms-rest-js` referenced by the old `ms-rest-azure-js`. Thus, TypeScript throws `...is not assignable to type...` errors.

While version reconciliation is fine by itself, technically it's a breaking change, so I wouldn't expect it to happen in a patch version.

**Expected behavior**

Don't make breaking changes in patch versions.

**Comment by amarzavery** [comment]
Oops. Sorry about that. Can you upgrade ms-rest-azure-js to 2.0.0. Then all the packages will use 2.x.x version of ms-rest-js

**Comment by mikesprague** [comment]
Having the same issue and only using `@azure/ms-rest-nodeauth` - not using `@azure/ms-rest-azure-js` - the update from `2.0.2` to `2.0.3` is what's causing existing working code to fail. 

Pinning to `2.0.2` "fixes" for now but no one is expecting breaking changes in a patch release.

**Comment by amarzavery** [comment]
please use version 2.0.4. This should fix your issue.
