### ISSUE TITLE
Add support for user-assigned identities in MSIAppServiceTokenCredentials

### ISSUE THREAD

**Issue by TenKeyAngle** [Azure/ms-rest-nodeauth#79]
**Package Version**: _______
- [ ] **nodejs**
   - **nodejs version**: 3.0.3

**Describe the bug**
Azure supports two types of managed identities: system-assigned and user-assigned. Currently, this library does not support passing in client_id and/or object_id in the MSIAppServiceTokenCredentials, which is required for function apps with multiple user-assigned identities.

**Additional context**
Note that this is similar to issue #58, only for AppServiceCredentials and not VM.

**Comment by emily-curry** [comment]
Fixed in the linked PR. In the meantime, you can import into your application `MSIAppServiceTokenCredentials`, extend that class, and override `prepareRequestOptions` to make the correct request. 

```ts
import { RequestPrepareOptions, WebResource } from '@azure/ms-rest-js';
import { MSIAppServiceOptions, MSIAppServiceTokenCredentials } from '@azure/ms-rest-nodeauth';

interface MSIAppServiceOptionsExtended extends MSIAppServiceOptions {
  clientId?: string;
}

export class MSIAppServiceTokenCredentialsExtended extends MSIAppServiceTokenCredentials {
  public static async loginWithAppServiceMSI(options: MSIAppServiceOptionsExtended) {
    const creds = new MSIAppServiceTokenCredentialsExtended(options);
    await creds.getToken();
    return creds;
  }

  protected clientId?: string;
  constructor(options: MSIAppServiceOptionsExtended) {
    super(options);
    this.clientId = options.clientId;
  }

  protected prepareRequestOptions() {
    const endpoint = this.msiEndpoint.endsWith("/") ? this.msiEndpoint : `${this.msiEndpoint}/`;
    const reqOptions: RequestPrepareOptions = {
      url: endpoint,
      headers: {
        secret: this.msiSecret,
      },
      queryParameters: {
        "resource": this.resource,
        "api-version": this.msiApiVersion,
        "clientid": this.clientId,
      },
      method: "GET",
    };

    const webResource = new WebResource();
    return webResource.prepare(reqOptions);
  }
}
```

Then `MSIAppServiceTokenCredentialsExtended.loginWithAppServiceMSI` can be used for generating credentials.
