### ISSUE TITLE
msRestNodeAuth.interactiveLoginWithAuthResponse() with proxy settings

### ISSUE THREAD

**Issue by mguirao** [Azure/ms-rest-nodeauth#80]
I'm looking for guidance on **how to use my corporate proxy** when using the interactive login
msRestNodeAuth.interactiveLoginWithAuthResponse().
Is it supported ? how should I proceed ?

When i'm on an open network, it works well, but when on corporate network, it fails : 
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXX to authenticate.  
Exception : Error: connect ETIMEDOUT 13.87.15.139:443
```
Thanks,

**Comment by thecherrytree** [comment]
If you are on mac or windows you could configure CNTLM
