### ISSUE TITLE
TypeError: fetch is not a function

### ISSUE THREAD

**Issue by natmegs** [Azure/ms-rest-nodeauth#82]
**Package Version**: "^3.0.3"
- [x] **nodejs**
   - **nodejs version**: 12.9.1
   - **os name/version**: macOS 10.13.6

**Describe the bug**
I'm trying to use this package in my Node app (also using Typescript) for authentication via `loginWithServicePrincipalSecretWithAuthResponse`. I am getting the following error: `TypeError: fetch is not a function`. 

This **does not** happen when I use the `ms-rest-azure` package, but this package does not seem to be compatible with others that I need to use such as `@azure/arm-subscriptions`.

**To Reproduce**
Steps to reproduce the behaviour:
```
import * as msRestNodeAuth from "@azure/ms-rest-nodeauth";
msRestNodeAuth.loginWithServicePrincipalSecretAuthResponse(
    clientID,
    clientSecret,
    tenantID
  ).then((r) => console.log("Authenticated")).catch(e => {
    console.log(e)
    throw e;
  });
```

Any help appreciated!

**Expected behavior**
Expect to be able to receive the auth response.

**Additional context**
I've gotten the suggestion that the browser Fetch API needs to be polyfilled but this seems strange if the package is meant to be used in Node, and even trying the polyfill just produced new TypeErrors.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @natmegs 

@daviwil, Can you please take a look at this?

**Comment by daviwil** [comment]
Hey @natmegs, can you share your `tsconfig.json`?  Make sure the your `lib` section contains the `dom` library otherwise the typings for `fetch` won't be present.  You shouldn't need to use a polyfill on your own, `ms-rest-js` takes care of that for you.

**Comment by natmegs** [comment]
@daviwil Thanks for looking into this! I tried adding "dom" to the lib section but am unfortunately still seeing the same error. Here's my updated tsconfig
```
{
  "extends": "../../tsconfig",
  "compilerOptions": {
    "baseUrl": ".",
    "esModuleInterop": true,
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "moduleResolution": "node",
    "noEmit": false,
    "outDir": "dist",
    "paths": { "*": ["types/*"], ...},
    "rootDir": "../..",
    "skipLibCheck": true,
    "target": "ES2019"
  },
  "include": ["src/**/*", ...],
  "exclude": ["**/__tests__/*"]
}
```

**Comment by natmegs** [comment]
After a bunch of experimentation, this issue was resolved by adding `"dom.iterable"` to `compilerOptions.lib`. This was a pretty major time sink so maybe it would be helpful to others if the specific tsconfig requirements of this package were documented somewhere 🙂

**Comment by ramya-rao-a** [comment]
Thanks @natmegs 

cc @xirzec and @willmtemple regarding tsconfig requirements and on how we can better document them.
