### ISSUE TITLE
Package dependency on adal-node (being deprecated) needs to be updated.

### ISSUE THREAD

**Issue by aflinchb** [Azure/ms-rest-nodeauth#84]
**Package Version**: 3.0.3
- [x] **nodejs**
   - **nodejs version**: 12.5
   - **os name/version**: Linux/Ubuntu 
- [ ] **browser**
    - **name/version**: ____
**Describe the bug**
ms-rest-nodeauth has a dependency on adal-node, which is being deprecated (and has dependencies on deprecated packages).  See issue: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/229#issuecomment-590518066.  Issue response suggests moving to msal (https://github.com/AzureAD/microsoft-authentication-library-for-js).

**To Reproduce**
See dependency in package.json files:
- adal-node in ms-rest-nodeauth : https://github.com/Azure/ms-rest-nodeauth/blob/master/package.json
- see request package dependency in adal-node: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/package.json
- See request deprecation information: https://github.com/request/request/issues/3142

**Expected behavior**
The package does not have deprecated dependencies.

**Comment by Jonlondon** [comment]
Please use node-fetch to fix this deprecation that exists since March 2019.

**Comment by lmshaffe** [comment]
As mentioned in this comment for adal-node: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/229#issuecomment-590518066

They won't be updating their library and are recommending to switch over to `msal js`. Should the fix be to replace adal-node with this new library?

**Comment by daviwil** [comment]
Hi all, `ms-rest-nodeauth` is currently in "maintenance mode" meaning that we won't be making any major investments like rewriting it to support new/different dependency libraries, etc.

The new [`@azure/identity`](https://www.npmjs.com/package/@azure/identity) library does use `msal.js` and `node-fetch` and also provides a much more convenient interface to AAD v2.  That said, not all Azure libraries support it yet (especially many of the `@azure/arm-*` libraries).  We will be gradually updating all of those libraries to provide support over the coming months.
