### ISSUE TITLE
MSIAppServiceTokenCredentials doesn't support single user-assigned managed identities

### ISSUE THREAD

**Issue by wuzhuoqing** [Azure/ms-rest-nodeauth#86]
Package Version: _______
nodejs
nodejs version: 3.0.3
Describe the bug
Azure supports two types of managed identities: system-assigned and user-assigned. Currently, MSIAppServiceTokenCredentials doesn't support user-assigned identities.

**To Reproduce**
1. 
Create node.js function app, assign only one user-assigned identity
const msRestNodeAuth = require("@azure/ms-rest-nodeauth");
const creds = await msRestNodeAuth.loginWithAppServiceMSI();

**Expected behavior**
creds return successfully

**Screenshots**
Exception: Error: Invalid token response, did not find tokenType. Response body is: {"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"d7e4de93-374a-428f-b6c9-21d9c42966f5"}
Stack: Error: Invalid token response, did not find tokenType. Response body is: {"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"d7e4de93-374a-428f-b6c9-21d9c42966f5"}
    at MSIAppServiceTokenCredentials.<anonymous> (/home/site/wwwroot/node_modules/@azure/ms-rest-nodeauth/dist/lib/credentials/msiAppServiceTokenCredentials.js:70:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/site/wwwroot/node_modules/@azure/ms-rest-nodeauth/dist/lib/credentials/msiAppServiceTokenCredentials.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Additional context**
This maybe a bug in backend MSI agent where it should return token when only one user-assigned identity is available. However don't know if the backend MSI agent is open source or how to create issue for that.

Note that this is similar to https://github.com/Azure/ms-rest-nodeauth/issues/79, but when there is only one user-assigned identity so the client id should not be needed.

Even though the [doc](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=javascript) says "If omitted, the system-assigned identity is used." it is not user friendly as the code will need to know what is the only client id and not consistent with vmMSI where it can get token without problem.
creds = await msRestNodeAuth.loginWithVmMSI();

**Comment by sadasant** [comment]
This was fixed by this pull request https://github.com/Azure/ms-rest-nodeauth/pull/85 as far as my tests can confirm. A new version will be released this week.

**Comment by sadasant** [comment]
I'll be closing this for now! Please let us know if we've missed something, @wuzhuoqing
