### ISSUE TITLE
Intermittent Linux App Service Login Failures with MSI

### ISSUE THREAD

**Issue by fcstring31** [Azure/ms-rest-nodeauth#87]
**Package Version**: 3.0.3
- [ ] **nodejs**
   - **nodejs version**: 10.14
   - **os name/version**: Linux App Service - Unix 4.4.0.128

**Describe the bug**
If `MSIAppServiceOptions` does not have `msiEndpoint` and `msiSecret` explicitly defined, login to a Key Vault fails intermittently. This despite confirming in Kudu that `MSI_ENDPOINT` and `MSI_SECRET` environment variables exist after enabling the system-assigned Managed Service Identity. I could most reliably cause a login failure by updating app settings or performing an app restart, though it would also suddenly fail after an arbitrary amount of time with no changes or restarts. I could get login to work again by fully stopping the app, waiting a few seconds, and then starting it.
Other steps, like re-deploying or spinning up an entirely new app service, did not improve the situation.

**To Reproduce**
1. Create Linux App Service on Node 10.14 runtime
2. Enable system-assigned MSI
3. Use `loginWithAppServiceMSI` to connect to a Key Vault
4. Set only the `resource` parameter in `MSIAppServiceOptions`
5. Wait a while or update app settings

**Example Stack Trace**

>Error in loginWithMSI Error: Invalid token response, did not find tokenType. Response body is: {"statusCode":503,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":""}
at MSIAppServiceTokenCredentials.<anonymous> (/home/site/wwwroot/node_modules/@azure/ms-rest-nodeauth/dist/lib/credentials/msiAppServiceTokenCredentials.js:70:23)
at Generator.next (<anonymous>)
at fulfilled (/home/site/wwwroot/node_modules/@azure/ms-rest-nodeauth/dist/lib/credentials/msiAppServiceTokenCredentials.js:6:58)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Workaround/Resolution**
I was able to correct this instability by explicitly defining the endpoint and secret properties like so:
`keyVaultOptions: MSIAppServiceOptions = {msiEndpoint: process.env.MSI_ENDPOINT, 
msiSecret: process.env.MSI_SECRET, 
resource: https://vault.azure.net};`

Based on 

> Either provide this parameter or set the environment variable `MSI_ENDPOINT`/`MSI_SECRET`

 in [msiAppServiceTokenCredentials.ts](https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/credentials/msiAppServiceTokenCredentials.ts), lines 13 and 19, this explicit definition doesn't seem like it should be necessary, as the environment variables are set when the system-assigned MSI is enabled.

**Comment by daviwil** [comment]
Hi @fcstring31, this instability is concerning, we will look into it.  Out of curiosity, have you tried this with a Windows App Service to see if you see the same instability?

**Comment by fcstring31** [comment]
Hey @daviwil, I haven't. This was something we were trying to sort out pre-go-live, so we were just trying to make this app work.
  
Curiously, we just started seeing failures again with MSI login, though the app has been running for a couple months and is set to "always on." I unfortunately don't have any other details to offer right now, but will keep digging and add comments here if I find anything relevant.

**Comment by fcstring31** [comment]
This latest instance of token retrieval issues just went away after about 24 hours. Before then, I couldn't get it to work no matter what I tried. It only affected our test app - prod continued working - so it may have been something that affected the servers behind our app service plan.

**Comment by ramya-rao-a** [comment]
Thanks for getting back to us with last status @fcstring31 

Closing this issue as you no longer see the problem. Please feel free to log a new issue if you encounter any other problem
