### ISSUE TITLE
Samples for getting MSI from App Service should use IDENTITY_ENDPOINT

### ISSUE THREAD

**Issue by dpolivy** [Azure/ms-rest-nodeauth#88]
This is a doc issue, not a code issue.

The sample showing how to [login using an MSI from App Service](https://github.com/Azure/ms-rest-nodeauth#msi-managed-service-identity-based-login-from-an-appservice-or-azure-function-created-in-azure) contains the following snippet:
````
const options: msRestNodeAuth.MSIAppServiceOptions = {
  msiEndpoint: "http://127.0.0.1:41741/MSI/token/";
}
````

However, per the [App Service documentation](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=javascript#obtain-tokens-for-azure-resources), one is supposed to use the environment variable `IDENTITY_ENDPOINT` to get the URL for the token service.

It took me a little bit to figure this out. The sample code in the README would be more effective if it used this in the example (and perhaps linked to the App Service page for more details), e.g.:
````
const options: msRestNodeAuth.MSIAppServiceOptions = {
  msiEndpoint: process.env["IDENTITY_ENDPOINT"]
}
````

**Comment by sadasant** [comment]
@dpolivy Thank you, Dan!

We will be improving the documentation based on your feedback. We appreciate your interest in our projects!

**Comment by dpolivy** [comment]
@sadasant Thanks! I just took a look at the linked PR and added one quick comment for you, hope it is useful :) But yes, looks like the changes may address my feedback.

**Comment by sadasant** [comment]
Thank you @dpolivy !

**Comment by ramya-rao-a** [comment]
With the latest version 3.0.5 of the package, `IDENTITY_ENDPOINT` and `IDENTITY_SECRET` environment variables will be respected when logging in using MSI from App Service.

Thanks for reporting @dpolivy
