### ISSUE TITLE
Checking auth status with ms-rest-nodeauth

### ISSUE THREAD

**Issue by hsheikhali** [Azure/ms-rest-nodeauth#92]
I have a question .. is there a way to use ms-rest-nodeauth to check whethe or not I am authenticated? This will help reduce the amount of times I need to authenticate if I have to run the script again.

For example, using the azure CLI after I do `az login` I don't need to run the command unless I have logged out of azure portal.

**Comment by ramya-rao-a** [comment]
Once you get a credential using any of the authentication methods in the `@azure/ms-rest-nodeauth` package, that credential will be valid for future use with the Azure SDKs that it supports until the point permissions are changed explicitly. You can use the same credential with multiple Azure SDKs as well.

Can you elaborate a scenario where you would need a check like what you described?

**Comment by daviwil** [comment]
@hsheikhali `ms-rest-nodeauth` does not cache any credentials across executions of a program or script that uses it.  It is possible to implement your own token cache which stores tokens to the local disk to be used in future runs, though I don't recommend doing this unless you're going to provide a reasonable level of security for the persisted cache on disk.

All login methods in `ms-rest-nodeauth` accept an `AzureTokenCredentialsOptions` parameter which has a `tokenCache` field which you can configure to use your own cache implementation: 

https://github.com/Azure/ms-rest-nodeauth/blob/31285f9e384c73ab5c0179565c328f5534a50679/lib/login.ts#L72

You can see the default in-memory cache implementation from adal-node here for an example of how to write such a cache: 

https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/81ff31dd612cae6cd69a9a7452171b7af792be9f/lib/memory-cache.js

**Comment by hsheikhali** [comment]
Hey @daviwil,

I decided to take that approach. Storing the response on local disk and attempting to reuse it will almost always throw an error. You need to pass the token to generate credentials that can be used again.

In terms of persisted cache and secrets and security. I think Ive found a solution that will help me out for now. So we should be good.

Thanks for reaching out though! I appreciate it!

**Comment by daviwil** [comment]
Glad to hear you found a workaround @hsheikhali!  Happy to help.
