### ISSUE TITLE
Issue with 3.0.4 version: loginWithServicePrincipalSecret is not declared writable or has no setter

### ISSUE THREAD

**Issue by sarmista-jv** [Azure/ms-rest-nodeauth#94]
We have been using 3.0.0 version of this module. This module was working fine until the new release 3.0.4 package(published on May-27-2020). When we are trying to use this module in our code, we are seeing the below error. Can you please help us resolve this?
Below is the method we are using in our code,
_export function withServicePrincipalSecret(clientId: string, secret: string, domain: string): Promise<ApplicationTokenCredentials>;_
**Error:**
loginWithServicePrincipalSecret is not declared writable or has no setter

**Comment by daviwil** [comment]
Hi @sarmista-jv - this update was released unexpectedly due to an automation error so we had to deprecate it.  Please roll back to 3.0.3 for now.  Thanks!
