### ISSUE TITLE
is master up to date?

### ISSUE THREAD

**Issue by g-k** [Azure/ms-rest-nodeauth#95]
Is master up to date? It looks like the most recent commit on master is from Aug 22nd 2019 for version 3.0.3 and since then versions 3.0.4 and 2.0.5 were published. 

Is the code for versions 3.0.4 and 2.0.5 available? Is the master head commit `adea8415de97a8076006fbd9948123d09dfdd78d` v3.0.3?

Thanks!

**Describe the bug**

Missing source for versions 3.0.4 and 2.0.5 on master branch. Unclear on whether commit `adea8415de97a8076006fbd9948123d09dfdd78d` was published as 3.0.3.

**Expected behavior**

Source and a reproducible build or build log publicly available with a hash we can confirm against the npm registry. Ideally with releases with signed tags on GH.

**Comment by daviwil** [comment]
Thanks for pointing this out.  I'm not exactly certain where 3.0.4 came from, investigating that now.  We've got a parallel branch called [`v2x`](https://github.com/Azure/ms-rest-nodeauth/tree/v2x) for hotfixes to the 2.0.0 series, you can see the commit for 2.0.5 there.

**Comment by daviwil** [comment]
OK, I now know how this happened.  Through a mistake of release automation, a CI job from PR #91 got shipped by accident.  The version was bumped in this PR, leading to the release getting shipped after a field in the release automation pipeline was selected incorrectly.  My apologies!  If you run into any trouble with that release, please stick to 3.0.3 for now until we get a chance to correct the issue.

/cc @sadasant @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Version 3.0.4 has been marked as deprecated.
Version 3.0.3 which is in the master branch should appear as the latest version on npm

Thanks a lot for reporting @g-k!

**Comment by g-k** [comment]
Thank you! I appreciate your quick response.
